language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements/test.txt
  - pip install -q Django==$DJANGO_VERSION
script:
  - coverage run --source=contact_form example/manage.py test
  - coverage report --show-missing
  - flake8 contact_form

env:
  - DJANGO_VERSION=1.11.9
  - DJANGO_VERSION=2.0.1
